### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by gloeyisk** [Magisk-Modules-Repo/OPportapps#1]
It seems when I've enabled the weather, that "Never Settle" text disappeared and replaced with current weather? And I can't get rid of this weather even the app disabled.
Is it possible reverted the widget to "Never Settle" text?

**Comment by rajdedhia10** [comment]
> It seems when I've enabled the weather, that "Never Settle" text disappeared and replaced with current weather? And I can't get rid of this weather even the app disabled.
> Is it possible reverted the widget to "Never Settle" text?

Disable the Weather app ->Remove the widget -> Clear Data of OnePlus Widget app -> Add Widget again. It should stay on "Never Settle" text.
This should work.

**Comment by rajdedhia10** [comment]
I'm working on Launcher but it's crashing on some devices. I'll add it as soon as it is stable.

**Comment by rajdedhia10** [comment]
> > > It seems when I've enabled the weather, that "Never Settle" text disappeared and replaced with current weather? And I can't get rid of this weather even the app disabled.
> > > Is it possible reverted the widget to "Never Settle" text?
> > 
> > 
> > Disable the Weather app ->Remove the widget -> Clear Data of OnePlus Widget app -> Add Widget again. It should stay on "Never Settle" text.
> > This should work.
> 
> Let me give a try.
> Also can you port the launcher? It'll matched with your ported widget and weather apps.
> Thanks.

I'm working on Launcher but it's crashing on some devices. I'll add it as soon as it is stable.
